### PR TITLE
new cool emacs suffs added! check it out!

### PR DESCRIPTION
**Pull request by rhoit**
* sort words
* window-numbering
* nuking trailing lines
* .emacs autoload lisp-mode
* re-indented .emacs config

### CODE REVIEW

**Comment by krazedkrish** [comment]
:+1: 
:sunglasses:

**Comment by rhoit** [comment]
congrats you successfully merged the pull request from 3 years ago.

**Comment by krazedkrish** [comment]
congrats you created a successful pull request from 3 years ago, when there is no emacs in the my-config! lol :smile_cat:

**Comment by zerOnepal** [comment]
हाहााहाहा

**Pull request merged**
